apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron-job-hello
  namespace: "producer-namespace"
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          securityContext:
            runAsUser: 1000
          containers:
          - name: busybox-hello-world
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
