apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  namespace: "producer-namespace"
spec:
  template:
    metadata:
      name: test-job
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
