apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "test-networkpolicy-egress"
  namespace: "producer-namespace"
spec:
  #Which pods will this rules apply
  podSelector:
    matchLabels:
      app: producer-application
  policyTypes:
  - Egress
  #Which type of netpol will use
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: "consumer-namespace"
      podSelector:
        matchLabels:
          app: consumer-application
    ports:
      - protocol: TCP
        port: 8081